Src/Models/Coordinate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ex3.Models
{
    public class Coordinate
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}

Src/Models/InfoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Web;

namespace Ex3.Models
{
    public class InfoModel
    {
        private static InfoModel s_instace = null;

        public static InfoModel Instance
        {
            get
            {
                if (s_instace == null)
                {
                    s_instace = new InfoModel();
                }
                return s_instace;
            }
        }

        private IPEndPoint iPEndPoint;
        private TcpClient tcpClient;

        private bool isConnected;

        public Coordinate Coordinate { get; set; }

        public InfoModel()
        {
            isConnected = false;

            Coordinate = new Coordinate();
        }

        public void Connect(string ip, int port)
        {
            
            if (isConnected)
            {
                Disconnect();
            }
            tcpClient = new TcpClient();

            iPEndPoint = new IPEndPoint(IPAddress.Parse(ip), port);
            tcpClient.Connect(iPEndPoint);

            isConnected = true;
            
        }

        public void Disconnect()
        {
            if (isConnected)
            {
                tcpClient.Close();
                isConnected = false;
            }
        }

        private double parseDoubleFromMessage(string s)
        {
            int i1 = s.IndexOf("'"),
                i2 = s.LastIndexOf("'");
            s = s.Substring(i1 + 1, i2 - i1 - 1);
            return double.Parse(s);
        }

        public Coordinate GetCoordinate()
        {
            if (isConnected)
            {
                using (NetworkStream stream = tcpClient.GetStream())
                using (System.IO.StreamReader reader = new System.IO.StreamReader(stream))
                using (System.IO.StreamWriter writer = new System.IO.StreamWriter(stream))
                {
                    
                    writer.Write("get /position/longitude-deg\r\n");
                    writer.Flush();
                    string lon = reader.ReadLine();

                    writer.Write("get /position/latitude-deg\r\n");
                    writer.Flush();
                    string lat = reader.ReadLine();

                    this.Coordinate.Longitude = parseDoubleFromMessage(lon);
                    this.Coordinate.Latitude = parseDoubleFromMessage(lat);
                    
                }
            }
            else
            {
                this.Coordinate.Longitude = 0.0;
                this.Coordinate.Latitude = 0.0;
            }

            return this.Coordinate;
        }

        public Coordinate GetRudderThrottle()
        {
            if (isConnected)
            {
                using (NetworkStream stream = tcpClient.GetStream())
                using (System.IO.StreamReader reader = new System.IO.StreamReader(stream))
                using (System.IO.StreamWriter writer = new System.IO.StreamWriter(stream))
                {

                    writer.Write("get /controls/flight/rudder\r\n");
                    writer.Flush();
                    string lon = reader.ReadLine();

                    writer.Write("get /controls/engines/current-engine/throttle\r\n");
                    writer.Flush();
                    string lat = reader.ReadLine();

                    this.Coordinate.Longitude = parseDoubleFromMessage(lon);
                    this.Coordinate.Latitude = parseDoubleFromMessage(lat);

                }
            }
            else
            {
                this.Coordinate.Longitude = 0.0;
                this.Coordinate.Latitude = 0.0;
            }

            return this.Coordinate;
        }
    }
}

Src/Controllers/MainController.cs
using Ex3.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ex3.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Default()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Display(string ip, int port)
        {
            System.Net.IPAddress p;
            if (System.Net.IPAddress.TryParse(ip, out p) == false)
            {
                // Load Travel
                ViewBag.Filename = ip;
                ViewBag.Frequency = port;

                return View("LoadTravel");
            }
            else
            {
                // Display
                InfoModel infoModel = InfoModel.Instance;
                infoModel.Connect(ip, port);

                ViewBag.Coordinate = infoModel.GetCoordinate();

                infoModel.Disconnect();

                return View();
            }
        }

        [HttpGet]
        public ActionResult DisplayTravel(string ip, int port, int frequency)
        {
            ViewBag.Ip = ip;
            ViewBag.Port = port;
            ViewBag.Frequency = frequency;

            return View();
        }

        [HttpGet]
        public ActionResult SaveTravel(string ip, int port, int frequency, int time, string filename)
        {
            ViewBag.Ip = ip;
            ViewBag.Port = port;
            ViewBag.Frequency = frequency;
            ViewBag.Time = time;
            ViewBag.Filename = filename;

            return View();
        }

        public const string SCENARIO_FILE = "~/App_Data/{0}.txt";

        public string LoadFromFile(string filename, int lineNumber)
        {
            string s;
            string path = System.Web.HttpContext.Current.Server.MapPath(String.Format(SCENARIO_FILE, filename));

            using (TextReader tr = new StreamReader(path))
            {
                for (int i = 1; i < lineNumber; i++)
                    tr.ReadLine();
                s = tr.ReadLine();
                tr.Close();
            }
            if (s == null || s == "")
            {
                return "";
            }
            else {
                return s.Substring(0, s.IndexOf("+"));
            }
        }

        public void SaveToFile(string filename, string line, string ip, int port)
        {
            string path = System.Web.HttpContext.Current.Server.MapPath(String.Format(SCENARIO_FILE, filename));

            line += "+" + GetStringRudderThrottle(ip, port);

            TextWriter textWriter = new StreamWriter(path, true);
            textWriter.WriteLine(line);
            textWriter.Close();
        }

        public string GetStringCoordinate(string ip, int port)
        {
            InfoModel infoModel = InfoModel.Instance;
            infoModel.Connect(ip, port);

            Coordinate coordinate = infoModel.GetCoordinate();

            infoModel.Disconnect();

            return coordinate.Longitude.ToString() + " " + coordinate.Latitude.ToString();
        }

        public string GetStringRudderThrottle(string ip, int port)
        {
            InfoModel infoModel = InfoModel.Instance;
            infoModel.Connect(ip, port);

            Coordinate coordinate = infoModel.GetRudderThrottle();

            infoModel.Disconnect();

            return coordinate.Longitude.ToString() + " " + coordinate.Latitude.ToString();
        }
    }
}

Src/Views/Main/Default.cshtml

@{
    ViewBag.Title = "Default";
}

<h2>Default</h2>


Src/Views/Main/Display.cshtml
@{
    ViewBag.Title = "Display";
}

<style>
    .canvas {
        background-image: url("/Content/export-map-share.png");
        background-size: 100% 100%;
    }
</style>

<canvas class="canvas" id="canvas"></canvas>

<script>
    // Taking coordinate
    var lon = @ViewBag.Coordinate.Longitude;
    var lat = @ViewBag.Coordinate.Latitude;

    var c = document.getElementById("canvas");

    // Setting canvas size
    c.width = window.innerWidth;
    c.height = window.innerHeight;

    // Setting canvas position
    c.style.left = "0px";
    c.style.top = "0px";
    c.style.position = "absolute";

    // Normalizing coordinate according to the screen
    lon = (lon + 180) * (window.innerWidth / 360);
    lat = (lat + 90) * (window.innerHeight / 180);

    var ctx = c.getContext("2d");

    // Drawing black-red point on canvas
    // Big black dot
    ctx.beginPath();
    ctx.arc(lon, lat, 12, 0, 2 * Math.PI);
    ctx.fillStyle = "black";
    ctx.fill();

    // Small red dot
    ctx.beginPath();
    ctx.arc(lon, lat, 9, 0, 2 * Math.PI);
    ctx.fillStyle = "red";
    ctx.fill();
</script>

Src/Views/Main/DisplayTravel.cshtml
@{
    ViewBag.Title = "DisplayTravel";
}

<style>
    .canvas {
        background-image: url("/Content/export-map-share.png");
        background-size: 100% 100%;
    }
</style>


<canvas class="canvas" id="canvas"></canvas>

<script>
    // Global variables - contain current and recent coordinates
    var oldLon, newLon, oldLat, newLat;

    initScreen();
    drawPoint();
    setInterval(myTimer, 1000 * @ViewBag.Frequency);

    /*
     * Gets a new updated coordinate.
     * Draws a line connecting current and recent coordinate.
     */
    function myTimer() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate using ajax POST
        $.post("@(Url.Action("GetStringCoordinate", "Main"))", { ip: "@ViewBag.Ip", port: @ViewBag.Port }).done(function (data) {
            // Process data
            var i = data.indexOf(" "), l = data.length;
            newLon = normalizeLon(parseFloat(data.substring(0, i)));
            newLat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Draw a line
            drawLine(oldLon, oldLat, newLon, newLat);

            // Update recent coordinate
            oldLon = newLon;
            oldLat = newLat;
        });
    }

    /*
     * Initialize the canvas (size and position).
     */
    function initScreen() {
        var c = document.getElementById("canvas");

        // Setting canvas size
        c.width = window.innerWidth;
        c.height = window.innerHeight;

        // Setting canvas position
        c.style.left = "0px";
        c.style.top = "0px";
        c.style.position = "absolute";
    }

    /*
     * Normalize longitude according to canvas size.
     */
    function normalizeLon (value) {
        return (value + 180) * (window.innerWidth / 360);
    }

    /*
     * Normalize latitude according to canvas size.
     */
    function normalizeLat(value) {
        return (value + 90) * (window.innerHeight / 180);
    }

    /*
     * Gets a new updated coordinate.
     * Draws a point showing current coordinate.
     */
    function drawPoint() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate using ajax POST
        $.post("@(Url.Action("GetStringCoordinate", "Main"))", { ip: "@ViewBag.Ip", port: @ViewBag.Port }).done(function (data) {
            // Process data
            var i = data.indexOf(" "), l = data.length;
            var lon = normalizeLon(parseFloat(data.substring(0, i)));
            var lat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Drawing black-red point on canvas
            // Big black dot
            ctx.beginPath();
            ctx.arc(lon, lat, 12, 0, 2 * Math.PI);
            ctx.fillStyle = "black";
            ctx.fill();

            // Small red dot
            ctx.beginPath();
            ctx.arc(lon, lat, 9, 0, 2 * Math.PI);
            ctx.fillStyle = "red";
            ctx.fill();

            // Update recent coordinate
            oldLon = lon;
            oldLat = lat;
            newLon = lon;
            newLat = lat;
        });
    }

    /*
     * Draws a line between 2 points on canvas.
     */
    function drawLine(x1, y1, x2, y2) {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Draws a red line
        ctx.strokeStyle = "red";
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
    }


</script>

Src/Views/Main/LoadTravel.cshtml
@{
    ViewBag.Title = "LoadTravel";
}

<style>
    .canvas {
        background-image: url("/Content/export-map-share.png");
        background-size: 100% 100%;
    }
</style>


<canvas class="canvas" id="canvas"></canvas>

<script>
    // Global variables - contain current and recent coordinates after and before normalization
    var oldLon, newLon, oldLat, newLat;
    // Current coordinate number (index)
    var lineNum = 1;

    initScreen();
    drawPoint();
    myInterval = setInterval(myTimer, 1000 * @ViewBag.Frequency);

    /*
     * Gets a new updated coordinate.
     * Draws a line connecting current and recent coordinate.
     */
    function myTimer() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate from flight file using ajax POST
        $.post("@(Url.Action("LoadFromFile", "Main"))", { filename: "@ViewBag.Filename", lineNumber: lineNum }).done(function (data) {
            // End of file
            if (data == null || data == "") {
                alert("Travel display has ended.");
                clearInterval(myInterval);
            }

            // Process data and normalize data
            var i = data.indexOf(" "), l = data.length;
            newLon = normalizeLon(parseFloat(data.substring(0, i)));
            newLat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Draw a line
            drawLine(oldLon, oldLat, newLon, newLat);

            // Update recent coordinate
            oldLon = newLon;
            oldLat = newLat;
        });

        lineNum = lineNum + 1;
    }

    /*
     * Initialize the canvas (size and position).
     */
    function initScreen() {
        var c = document.getElementById("canvas");

        c.width = window.innerWidth;
        c.height = window.innerHeight;

        c.style.left = "0px";
        c.style.top = "0px";
        c.style.position = "absolute";
    }

    /*
     * Normalize longitude according to canvas size.
     */
    function normalizeLon (value) {
        return (value + 180) * (window.innerWidth / 360);
    }

    /*
     * Normalize latitude according to canvas size.
     */
    function normalizeLat(value) {
        return (value + 90) * (window.innerHeight / 180);
    }

    /*
     * Gets a new updated coordinate.
     * Draws a point showing current coordinate.
     */
    function drawPoint() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate from flight file using ajax POST
        $.post("@(Url.Action("LoadFromFile", "Main"))", { filename: "@ViewBag.Filename", lineNumber: lineNum }).done(function (data) {
            var i = data.indexOf(" "), l = data.length;
            // Process data and normalize data
            var lon = normalizeLon(parseFloat(data.substring(0, i)));
            var lat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Drawing black-red point on canvas
            // Big black dot
            ctx.beginPath();
            ctx.arc(lon, lat, 12, 0, 2 * Math.PI);
            ctx.fillStyle = "black";
            ctx.fill();

            // Small red dot
            ctx.beginPath();
            ctx.arc(lon, lat, 9, 0, 2 * Math.PI);
            ctx.fillStyle = "red";
            ctx.fill();

            // Update recent coordinate
            oldLon = lon;
            oldLat = lat;
            newLon = lon;
            newLat = lat;
        });

        lineNum = lineNum + 1;
    }

    /*
     * Draws a line between 2 points on canvas.
     */
    function drawLine(x1, y1, x2, y2) {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Draws a red line
        ctx.strokeStyle = "red";
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
    }
</script>

Src/Views/Main/SaveTravel.cshtml
@{
    ViewBag.Title = "SaveTravel";
}

<style>
    .canvas {
        background-image: url("/Content/export-map-share.png");
        background-size: 100% 100%;
    }
</style>


<canvas class="canvas" id="canvas"></canvas>

<script>
    // Global variables - contain current and recent coordinates after and before normalization
    var oldLon, newLon, oldLat, newLat;
    var origLon, origLat;

    initScreen();
    drawPoint();
    myInterval = setInterval(myTimer, 1000 * @ViewBag.Frequency);
    setTimeout(stopFunc, 1000 * @ViewBag.Time);

    function stopFunc() {
        clearInterval(myInterval);
    }

    /*
     * Gets a new updated coordinate.
     * Draws a line connecting current and recent coordinate.
     */
    function myTimer() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate using ajax POST
        $.post("@(Url.Action("GetStringCoordinate", "Main"))", { ip: "@ViewBag.Ip", port: @ViewBag.Port }).done(function (data) {
            var i = data.indexOf(" "), l = data.length;

            // Process data
            origLon = parseFloat(data.substring(0, i));
            origLat = parseFloat(data.substring(i + 1, l));

            // Normalize data
            newLon = normalizeLon(parseFloat(data.substring(0, i)));
            newLat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Draw a line
            drawLine(oldLon, oldLat, newLon, newLat);

            // Saves current coordinate to flight file
            saveToFile();

            // Update recent coordinate
            oldLon = newLon;
            oldLat = newLat;
        });
    }

    /*
     * Saves current coordinate to flight file.
     */
    function saveToFile() {
        var lonLat = origLon + " " + origLat;
        if (lonLat != "undefined undefined") {
            $.post("@(Url.Action("SaveToFile", "Main"))", { filename: "@ViewBag.Filename", line: lonLat, ip: "@ViewBag.Ip", port: @ViewBag.Port });
        }
    }

    /*
     * Initialize the canvas (size and position).
     */
    function initScreen() {
        var c = document.getElementById("canvas");

        c.width = window.innerWidth;
        c.height = window.innerHeight;

        c.style.left = "0px";
        c.style.top = "0px";
        c.style.position = "absolute";
    }

    /*
     * Normalize longitude according to canvas size.
     */
    function normalizeLon (value) {
        return (value + 180) * (window.innerWidth / 360);
    }

    /*
     * Normalize latitude according to canvas size.
     */
    function normalizeLat(value) {
        return (value + 90) * (window.innerHeight / 180);
    }

    /*
     * Gets a new updated coordinate.
     * Draws a point showing current coordinate.
     */
    function drawPoint() {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Gets new coordinate using ajax POST
        $.post("@(Url.Action("GetStringCoordinate", "Main"))", { ip: "@ViewBag.Ip", port: @ViewBag.Port }).done(function (data) {
            var i = data.indexOf(" "), l = data.length;

            // Process data
            origLon = parseFloat(data.substring(0, i));
            origLat = parseFloat(data.substring(i + 1, l));

            // Normalize data
            var lon = normalizeLon(parseFloat(data.substring(0, i)));
            var lat = normalizeLat(parseFloat(data.substring(i + 1, l)));

            // Drawing black-red point on canvas
            // Big black dot
            ctx.beginPath();
            ctx.arc(lon, lat, 12, 0, 2 * Math.PI);
            ctx.fillStyle = "black";
            ctx.fill();

            // Small red dot
            ctx.beginPath();
            ctx.arc(lon, lat, 9, 0, 2 * Math.PI);
            ctx.fillStyle = "red";
            ctx.fill();

            // Saves current coordinate to flight file
            saveToFile();

            // Update recent coordinate
            oldLon = lon;
            oldLat = lat;
            newLon = lon;
            newLat = lat;
        });
    }

    /*
     * Draws a line between 2 points on canvas.
     */
    function drawLine(x1, y1, x2, y2) {
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");

        // Draws a red line
        ctx.strokeStyle = "red";
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
    }
</script>

Src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>


    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>